name: managedt
version: 0.1.0
github: "bartfrenk/managedt"
license: BSD3
author: "Bart Frenk"
maintainer: "bart.frenk@gmail.com"
copyright: "2018 Bart Frenk"

extra-source-files:
  - README.md

description: >-
  Please see the README on GitHub at
  <https://github.com/bartfrenk/managedt#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  ghc-options:
    - -Wall
  source-dirs: src
  dependencies:
    - monad-logger
    - mtl
